### ISSUE TITLE
'MuseModelConfig' object has no attribute 'scaled_fp8'

### ISSUE THREAD

**Issue by 807502278** [kijai/ComfyUI-MuseTalk-KJ#13]
```
got prompt
2024-11-01 17:29:21.581335 end_vram - start_vram: 0 - 0 = 0
2024-11-01 17:29:21.581335 #15 [EmptyImage]: 0.01s - vram 0b
Using xformers attention in VAE
Using xformers attention in VAE
2024-11-01 17:29:21.719690 end_vram - start_vram: 0 - 0 = 0
2024-11-01 17:29:21.719690 #4 [VAELoader]: 0.14s - vram 0b
!!! Exception during processing !!! 'MuseModelConfig' object has no attribute 'scaled_fp8'
Traceback (most recent call last):
  File "D:\AI\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\execution.py", line 165, in _map_node_over_list
    process_inputs({})
  File "D:\AI\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-MuseTalk-KJ-patch\nodes.py", line 80, in load_unet
    model = BaseModel(model_config)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\comfy\model_base.py", line 100, in __init__
    fp8 = model_config.optimizations.get("fp8", model_config.scaled_fp8 is not None)
                                                ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MuseModelConfig' object has no attribute 'scaled_fp8'

2024-11-01 17:29:22.745629 end_vram - start_vram: 0 - 0 = 0
2024-11-01 17:29:22.745629 #121 [UNETLoader_MuseTalk]: 1.03s - vram 0b
Prompt executed in 1.19 seconds
```

**Comment by 807502278** [comment]
"scaled_fp8" attribute added, but for some unknown reason, there is a clear boundary on the face
![image](https://github.com/user-attachments/assets/61f03dcc-54b9-4563-be4b-b0aa6a0a0107)

**Comment by jqy-yo** [comment]
请问怎么添加的
