### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by kotaxyz** [kijai/ComfyUI-MuseTalk-KJ#7]
i have rtx 3060ti with 8gb vram

[rgthree] Using rgthree's optimized recursive execution.
model_type EPS
!!! Exception during processing!!! 'MuseModelConfig' object has no attribute 'memory_usage_factor'
Traceback (most recent call last):
  File "I:\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "I:\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "I:\ComfyUI\ComfyUI\execution.py", line 70, in map_node_over_list
    results.append(getattr(obj, func)())
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-MuseTalk-KJ\nodes.py", line 77, in load_unet
    model = BaseModel(model_config)
  File "I:\ComfyUI\ComfyUI\comfy\model_base.py", line 97, in __init__
    self.memory_usage_factor = model_config.memory_usage_factor
AttributeError: 'MuseModelConfig' object has no attribute 'memory_usage_factor'

Prompt executed in 3.42 seconds

**Comment by kaidemc** [comment]
Error occurred when executing UNETLoader_MuseTalk:

'MuseModelConfig' object has no attribute 'memory_usage_factor'

File "C:\ComfyUI-aki-v1.3\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\ComfyUI-aki-v1.3\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\ComfyUI-aki-v1.3\execution.py", line 70, in map_node_over_list
results.append(getattr(obj, func)())
File "C:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-MuseTalk-KJ\nodes.py", line 77, in load_unet
model = BaseModel(model_config)
File "C:\ComfyUI-aki-v1.3\comfy\model_base.py", line 99, in __init__
self.memory_usage_factor = model_config.memory_usage_factor
